import type { DraftArtifact, EvidenceItem, ExecutionOutput, PlanStep } from './types';
import type { ApprovalRecord, ToolRegistry } from '../tools/toolRegistry';
import type { CommandName } from '../workflows/schema';
import type { PolicyMode } from './types';

function extractPrimaryQuery(rawInput: string, command: CommandName): string {
  const normalized = rawInput.replace(new RegExp(`^/${command}\\s*`, 'i'), '').trim();
  return normalized.length > 0 ? normalized : `workflow ${command}`;
}

function buildEmailDraftFromInput(rawInput: string, tools: ToolRegistry): DraftArtifact {
  const emailMatch = rawInput.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i);
  const to = emailMatch?.[0] ?? 'recipient@example.com';

  return tools.draftEmail({
    to,
    subject: 'Follow-up from Workflow OS',
    body: 'Quick follow-up. If this is still relevant, reply with your preferred next step and time.',
    objective: 'Preserve momentum without hard pressure.'
  });
}

function buildDraftFromIntent(rawInput: string, tools: ToolRegistry): DraftArtifact {
  const lower = rawInput.toLowerCase();

  if (lower.includes('calendar') || lower.includes('meeting')) {
    return tools.draftCalendarEvent({
      attendees: ['stakeholder@example.com'],
      title: 'Working Session',
      when: '2026-03-06T14:00:00-05:00',
      notes: 'Draft generated by Workflow OS; verify details before sending.'
    });
  }

  if (lower.includes('notion') || lower.includes('doc')) {
    return tools.draftNotionPatch({
      pageId: 'notion-page-id-placeholder',
      patch: '- Add summary section\n- Add owner + due date fields',
      rationale: 'User requested document update workflow.'
    });
  }

  return buildEmailDraftFromInput(rawInput, tools);
}

async function executeSideEffectFromIntent(
  rawInput: string,
  tools: ToolRegistry,
  approvalRecord: ApprovalRecord
): Promise<string> {
  const lower = rawInput.toLowerCase();

  if (lower.includes('calendar') || lower.includes('meeting')) {
    tools.gcal.executeCreateEvent(
      {
        attendees: ['stakeholder@example.com'],
        title: 'Working Session',
        when: '2026-03-06T14:00:00-05:00',
        notes: 'Execution from APPROVAL_REQUIRED mode.'
      },
      approvalRecord
    );
    return 'Executed approved calendar action via gcal connector.';
  }

  if (lower.includes('notion') || lower.includes('doc')) {
    tools.notion.executePatch(
      {
        pageId: 'notion-page-id-placeholder',
        patch: '- Add summary section\\n- Add owner + due date fields',
        rationale: 'Approved Notion update.'
      },
      approvalRecord
    );
    return 'Executed approved document patch via notion connector.';
  }

  const emailMatch = rawInput.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i);
  const to = emailMatch?.[0] ?? 'recipient@example.com';
  await tools.gmail.executeSend(
    {
      to,
      subject: 'Follow-up from Workflow OS',
      body: 'Approved send path executed.'
    },
    approvalRecord
  );
  return 'Executed approved email action via gmail connector.';
}

export async function executePlan(input: {
  command: CommandName;
  rawInput: string;
  steps: PlanStep[];
  tools: ToolRegistry;
  policyMode: PolicyMode;
  approvalRecord?: ApprovalRecord;
  executeApprovedSideEffects?: boolean;
}): Promise<ExecutionOutput> {
  const evidence: EvidenceItem[] = [];
  const drafts: DraftArtifact[] = [];
  const notes: string[] = [];
  const query = extractPrimaryQuery(input.rawInput, input.command);

  for (const step of input.steps) {
    if (step.requiresSideEffect) {
      if (
        input.policyMode === 'APPROVAL_REQUIRED' &&
        input.executeApprovedSideEffects &&
        input.approvalRecord?.approved
      ) {
        try {
          const executionNote = await executeSideEffectFromIntent(
            input.rawInput,
            input.tools,
            input.approvalRecord
          );
          notes.push(executionNote);
          continue;
        } catch (error) {
          drafts.push(buildDraftFromIntent(input.rawInput, input.tools));
          notes.push(
            `Approved execution blocked and converted to draft: ${(error as Error).message}`
          );
        }
        continue;
      }

      drafts.push(buildDraftFromIntent(input.rawInput, input.tools));
      notes.push('Side-effect intent converted to DraftPayload under policy gate.');
      continue;
    }

    if (step.tool === 'fileSearch') {
      const result = await input.tools.runFileSearch(query);
      evidence.push({ tool: result.tool, details: result.details, raw: result.raw });
      continue;
    }

    if (step.tool === 'webSearch') {
      const result = await input.tools.runWebSearch(query);
      evidence.push({ tool: result.tool, details: result.details, raw: result.raw });
      continue;
    }

    if (step.tool === 'computerUse') {
      const result = await input.tools.runComputerUse(query);
      evidence.push({ tool: result.tool, details: result.details, raw: result.raw });
      continue;
    }
  }

  if (evidence.length === 0) {
    notes.push('No tool evidence was required for this run.');
  }

  return {
    evidence,
    drafts,
    notes
  };
}
